# Reference: 
# - https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# - https://docs.docker.com/build/ci/github-actions/multi-platform/
# - https://docs.docker.com/engine/reference/commandline/manifest/

name: "Arduino IDE"

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/action.yaml
      - docker/Dockerfile

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/arduino_ide

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push amd64
        run: |
          cd docker
          docker buildx build --platform linux/amd64 -t ${{ env.REGISTRY_IMAGE }}:latest-amd64 --target amd64 --push .
      - name: Build and push arm64
        run: |
          cd docker
          docker buildx build --platform linux/arm64/v8 -t ${{ env.REGISTRY_IMAGE }}:latest-arm64v8 --target arm64 --push .
      - name: Create and push manifest (latest)
        run: |
          docker buildx imagetools create \
            -t ${{ env.REGISTRY_IMAGE }}:latest \
            ${{ env.REGISTRY_IMAGE }}:latest-amd64 \
            ${{ env.REGISTRY_IMAGE }}:latest-arm64v8
      - name: Create and push manifest (timestamp)
        run: |
          DATE=$(date +%Y%m%d)
          docker buildx imagetools create \
            -t ${{ env.REGISTRY_IMAGE }}:$DATE \
            ${{ env.REGISTRY_IMAGE }}:latest-amd64 \
            ${{ env.REGISTRY_IMAGE }}:latest-arm64v8